/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Native */

#ifndef _Included_Native
#define _Included_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Native
 * Method:    RayCast
 * Signature: (DDDDDDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_Native_RayCast
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     Native
 * Method:    render_col
 * Signature: ([DDIIDILSector;)[I
 */
JNIEXPORT jintArray JNICALL Java_Native_render_1col
  (JNIEnv *, jclass, jdoubleArray, jdouble, jint, jint, jdouble, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
